language: java
jdk:
  - oraclejdk8
dist: trusty
install: true

branches:
  only:
    - master
    - develop
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=API4KBs_kmdp-reasoning-service -Ppublic -q

deploy:
  - provider: script
    script: mvn deploy -DskipTests -Ppublic -s .travis.settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: mvn deploy -DskipTests -Ppublic -s .travis.settings.xml
    skip_cleanup: true
    on:
      branch: develop

addons:
  sonarcloud:
    organization: "api4kbs"
    token:
      secure: "EShQj5os1mtR1pcc9OA1GDuVtSCxHyBKBGidBGCchm5F3cdaBiXl8M3nyQ8Q4EN2hHsCi13xymooiBQszJaXV1hqSwEdrbiWW0b7HqBo5b0o2sLW32l1QhqiSt9ywaA2Jy64ER0feG3prmbhaWoecqFw9MSIgGzPo0Q2oXNnMPjZzoq/YMTjGClpRRau/dCrToJMy5heEgNUIfES9GQqFDKASNi0HsTiHpS5c2wlLjnwTMYIMrp2CJlqz5vOyH3h3BDdIzxhVhF0AWg6ogF/IFX0BagpYycR8DyDwOJQCCe2ZEJZXs7Yt54HrqAqX9EbBcdKem+UYSTJFUGPEfWJMEnyR3DghtOp79Hxys3Vk+KHpRUJrmY9+0qAsT1NaLFl5+/wf1cN6nzzv3gGDUXw7yYRysdpM2Hs9VJM2PsYiBe6e/qvzdiO1YSZkaQGlj86Rfpeu0NO/huIW6s7QaSlmlZy2ANxZwD/vLpGYJrjrFA4sGbEzE7OArHLFRDHwM3CkVssaIyRpCPefbINny3DZ07myYZA+wN03Lo4woud1mks/OX6Oe4mxXO42zeQ3yheLX6eRwnpX7gIYCKu4VC7+aHWycc4GeZgX1VkuP9AELiM7hsU8IZ/MADlk/3roFtDSepNSs8PcyPWUv/5ekCTcpL/l1bjfEvCx6VSsV2TqWQ="

env:
  global:
    - secure: "UHAYPqoKsH52TMadw4HU56RF5fJLB4tKnawqEH/z6MumZSPNh8QpMuRHeg7xnNPwj0RWZv9g22Va27zOoVBy/UgcbqWlTX1zKcWTTDTsFVxmXUI9FpMwTNlU9BX7/hIOVYTijHdDkOFR6r+jbE32C9panlJFV850gIvkpfn25eZEgS6L82VlMKvrjd3tiltqhP0qI61afGlalcYgGHuzLqEDiIgDDv7+KVhDiGvOPW5bJQPuq3F+7Atbw5x2crPE6qjR8v1UpXWIFMDULa/CXnc1jYNUNWFaGDoxdMhDHHYX3FOX8wfRmSDL5xgaQmlOfumIEmcd8DyCqisU1Lcr7eaANlOpVYRuFygPZ4NFFn5aXD/p1AAfgDHcSycInNUxSpz5uXElwgNe4luYgj7A+tDsLulpicJbtX0Oy/mYONo8Zv/BzvgmQvSikRd4kW+euefGMpozCc4w8E34bRcyE9SUOf/tkLjill6VeTmZy6eGUD2tP7izgD5Xx+G+JLF+E2AjNnJdbR7V6xSMdAYUS74PP/N8d/seY/l1ZCupxFubyKITRdDvkWsxEM+2EjLPoqIpy27LGoWmDxC8G1K9KLEfiEX6iy3PqI8zFfS/LXvbTPJ6kZzQsbr/osSmRxJJ285QtSK12iO2FCKU3xoHVYr3SHKzPBS2F8fJ18sTfnQ="
    - secure: "QBkiwZK+UCUxdJInGkptUEvhmiyq4pVB9ADm1fmdn7wmQwVXtzQ/u3tx3g4Os3J61uhHKXBOr2CCiJ56f3IugBE64SB6gMhKzQeyJwJqFa8VgpP+BRCS7mGvFUxVPdqrOdtTf+D8/ds3bWEAjCQv8EeqHEFEm1rYDVjAiLtqk5wjZvtT/ljUqEAGnroHx8yfI1j4BUt9QcAkEFQ9EemDDn4+hBELAit3HySA9zXETv9kuQKkvTZHGemlWFP51YWJOGd0taZ1jAxqd/Ckv30tZOn0UGPW4L2NzZ0g7eXcnUWQx0Q5eVa4NpMFs7e1MUmcVGy97n7/6kHZ0JmNV67OgOSH6zjGoM16N0qSHNjIxq+4S4DqNKveb4A5d/zRBrGtWTHlho+UBgSz5Lj6MOVhmdMmqWp/C53TO9mJthnDXG5o6/cSW3DuaZEspMCqSzQYED0JvnzgFXZRhjduMQUNvHWx1RwQmVjv70X/P+s3Sc0wuZoJhkUnDX+aFyZuo60oclrmpSBiMNWpyBBjqcwvENmgb1Jtn8ABJpIsvycFDer+o7Tlyv0ZJZREPJJaTuDUGAx9ekvvhzVoYPX07OY5dS9xaHqBctT2nUAcauQLhxlp2GgSwMN0EboQbpnCZQ4op4x3eJRuzfkkmJyD6Mq1mYFByJb9dHwpZbX4rsvbPdE="
